#! /bin/bash

docker kill kamon-grafana-dashboard
docker rm kamon-grafana-dashboard

docker run -d -p 80:80 -p 8000:8000 -p 8125:8125/udp -p 8126:8126 --name kamon-grafana-dashboard wavded/grafana_graphite
